name: Release

on:
  - workflow_dispatch

jobs:
  release:
    name: Release
    permissions:
      contents: write
      id-token: write
      packages: write
    uses: arktonix/cloud-native-utils/.github/workflows/package-release.yml@main
    with:
      package-name-slug: cartographer-golden-path-web
      package-name-display: Cartographer Golden Path Web
      registry-server: ghcr.io
      registry-username: ${{ github.actor }}
      image: ${{ github.repository }}
      version: 0.2.0
    secrets:
      pull-request-token: ${{ secrets.GH_ORG_PAT }}
